@startuml
title StudyTrackerParser parsing Aliases

start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command contains alias])
    :Get expanded
    command from alias;
    :Prepend expanded
    command to initial
    command;
else ([else])
endif

:Create new Command
based on command word
and arguments;

stop
@enduml
