@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam classFontSize 16
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

StudyTracker *-right-> "1" UniqueStudySpotList
StudyTracker *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueStudySpotList
UniqueTagList -[hidden]down- UniqueStudySpotList

UniqueTagList *-right-> "*" Tag
UniqueStudySpotList -right-> StudySpot

StudySpot -up-> "*" Tag

StudySpot *--> Name
StudySpot *--> Rating
StudySpot *--> OperatingHours
StudySpot *--> Address
StudySpot *--> Favourite
StudySpot *--> Amenities
StudySpot *--> StudiedHours
@enduml
