@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StudyTrackerParser" as StudyTrackerParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete n/Central Library")
activate LogicManager

LogicManager -> StudyTrackerParser : parseCommand("delete n/Central Library")
activate StudyTrackerParser

create DeleteCommandParser
StudyTrackerParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> StudyTrackerParser
deactivate DeleteCommandParser

StudyTrackerParser -> DeleteCommandParser : parse("n/Central Library")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> StudyTrackerParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> StudyTrackerParser
destroy DeleteCommandParser

StudyTrackerParser --> LogicManager : d
deactivate StudyTrackerParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteStudySpot(Central Library)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommand -[hidden]-> StudyTrackerParser
destroy DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
