@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classFontSize 16
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyStudyTracker <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class StudyTracker
Class ReadOnlyStudyTracker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class UniqueStudySpotList
Class UniqueFavouriteStudySpotList
Class StudySpot
Class Name
Class Rating
Class Address
Class OperatingHours
Class Amenities
Class StudiedHours
Class Favourite
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

StudyTracker .up.|> ReadOnlyStudyTracker

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyStudyTracker
ModelManager -left-> "1" StudyTracker
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

StudyTracker *--> "1" UniqueStudySpotList
StudyTracker *--> "1" UniqueFavouriteStudySpotList
UniqueStudySpotList --> "~* all" StudySpot
UniqueFavouriteStudySpotList --> "*" StudySpot
StudySpot *--> Name
StudySpot *--> Rating
StudySpot *--> OperatingHours
StudySpot *--> Address
StudySpot *--> Amenities
StudySpot *--> StudiedHours
StudySpot *--> Favourite
StudySpot *--> "*" Tag

Name -[hidden]right-> Rating
Rating -[hidden]right-> Address
Address -[hidden]right-> OperatingHours

ModelManager -->"~* filtered" StudySpot
@enduml
