@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
Class JsonSerializableUserPrefs
Class JsonAdaptedAlias
}

Interface Storage <<Interface>>
Class StorageManager

package "StudyTracker Storage" #F4F6F6{
Interface StudyTrackerStorage <<Interface>>
Class JsonStudyTrackerStorage
Class JsonSerializableStudyTracker
Class JsonAdaptedStudySpot
Class JsonAdaptedTag
Class JsonAdaptedAmenity
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" StudyTrackerStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> StudyTrackerStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonUserPrefsStorage ..> JsonSerializableUserPrefs
JsonSerializableUserPrefs --> "*" JsonAdaptedAlias

JsonStudyTrackerStorage .up.|> StudyTrackerStorage
JsonStudyTrackerStorage ..> JsonSerializableStudyTracker
JsonSerializableStudyTracker --> "*" JsonAdaptedStudySpot
JsonAdaptedStudySpot --> "*" JsonAdaptedTag
JsonAdaptedStudySpot --> "*" JsonAdaptedAmenity


@enduml
