@startuml
title Activity: Setting Themes

start
:Start app;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

repeat :Load Theme from model;
:Inject CSS file to Stage;
backward: Set new theme in model;

repeat while () is ([User selects new theme?])
-> [User exits app];

stop
@enduml
